server:
  port: ${SERVER_PORT:8087}

spring:
  application:
    name: notification-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${NOTIFICATION_SERVICE_DATABASE_URL:jdbc:postgresql://localhost:5432/notification_service}
    username: ${NOTIFICATION_SERVICE_DATABASE_USER:postgres}
    password: ${NOTIFICATION_SERVICE_DATABASE_PASSWORD}
  kafka:
    consumer:
      group-id: notification-service-id
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}

  jpa:
    generate-ddl: false
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        ddl-auto: none
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret-code: ${SECRET_KEY}
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
springdoc:
  swagger-ui:
    path: /docs/

